# Generated by Django 2.0.9 on 2018-10-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heroApiId', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('localized_name', models.CharField(max_length=200)),
                ('url_full_portrait', models.CharField(max_length=200)),
                ('url_large_portrait', models.CharField(max_length=200)),
                ('url_small_portrait', models.CharField(max_length=200)),
                ('url_vertical_portrait', models.CharField(max_length=200)),
            ],
        ),
    ]
